name: Go-pull_request

on:
  pull_request:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pre-req gpgme
      run:  sudo apt-get install libgpgme11 libgpgme-dev
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -tags include_gcs -v ./...

    - name: Test
      run: |
        # start tests
        go test -tags include_gcs -v ./... -coverprofile cover.out
    - uses: codecov/codecov-action@v2

